In [ ]:
import numpy as np

In [ ]:
#Matrix Addition


A= np.array( [ [1,2], [3,4] ])
B= np.array( [ [5,6], [7,8] ])
C= A+B
print("C matrix is (Addition) = ", np.array(C))

C matrix is (Addition) =  [[ 6  8]
 [10 12]]


In [ ]:
#Matrix_Subtraction
B= np.array( [ [1,2], [3,4] ])
A= np.array( [ [5,6], [7,8] ])
C= A-B
print("C matrix is (Subtraction) =  ", np.array(C))


C matrix is (Subtraction) =   [[4 4]
 [4 4]]


In [ ]:
#Matrix Multiplication

A= np.array( [ [1,2], [3,4] ])
B= np.array( [ [5,6], [7,8] ])
C= A * B
print("C matrix is (Multiplication ) = ", np.array(C))

C matrix is (Multiplication - Dot/Inner product) =  [[19 22]
 [43 50]]


In [ ]:
#Transpose

A = np.array( [[1 ,33],
              [2 ,34],
              [3 ,35]  ] )

B = np.array([ [4, 5, 6 ], [76,75,79] ])

print("Transpose of A = " , np.array( A.T ) )
print("Transpose of B = " , np.array( B.T) )



Transpose of A =  [[ 1  2  3]
 [33 34 35]]
Transpose of B =  [[ 4 76]
 [ 5 75]
 [ 6 79]]


In [ ]:
# Dot/inner product of 2 Vectors
# No need to explicitly mention as T for Transpose for vectors. It will be automatically calculate as B @ A.T

A = np.array([1,2,3])
B = np.array([4,5,6])
C  = np.dot(A,B)
print("C matrix is (Dot product) = ", C)


C matrix is (Dot product) =  32


In [ ]:
# Dot/inner product of 2 Vectors
# No need to explicitly mention as T for Transpose for vectors. It will be automatically calculate as B @ A.T

A = np.array([1,2,3])
B = np.array([4,5,6])
C  = A @ B
print("C matrix is (Dot product) = ", C)


In [ ]:
# Dot product of matrices using 2 matrices ( using dot function )
# We have to explicitly mention as T for Transpose for matrices

A = np.array([[1],
              [2],
              [3]])

B = np.array([[4],
              [5],
              [6]])
C  = np.dot(A.T,B)
print("C matrix is (Dot product) = ", C)


In [ ]:
# Dot product of matrices using 2 matrices ( using @ )
# We have to explicitly mention as T for Transpose for matrices

A = np.array([[1],
              [2],
              [3]])

B = np.array([[4],
              [5],
              [6]])
C  = A.T @ B
print("C matrix is (Dot product) = ", C)


C matrix is (Dot product) =  [[32]]


In [ ]:
# Outer product of matrices using 2 matrices ( using @ )
# We have to explicitly mention as T for Transpose for matrices

A = np.array([[1],
              [2],
              [3]])

B = np.array([[4],
              [5],
              [6]])
C  = A @ B.T
print("C matrix is (Dot product) = ", C)


C matrix is (Dot product) =  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
# Outer product of 2 vectors
# No need to explicitly mention as T for Transpose for vectors. It will be automatically calculate as B @ A.T


A = np.array( [ [1,2,3] ] )
B = np.array([ [4,5,6] ] )
C  = np.outer(A,B)
print("C matrix is (Outer product) = ", C)


C matrix is (Outer product) =  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
# Outer product of matrices using 2 matrices ( using outer function )
# We have to explicitly mention as T for Transpose for matrices

A = np.array([[1],
              [2],
              [3]])

B = np.array([[4],
              [5],
              [6]])
C  = np.outer(A, B.T)
print("C matrix is (Dot product) = ", C)


C matrix is (Dot product) =  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
#Determinant of a matrix
import numpy as np
A = np.array (
    [
        [1,2,2],
        [4,2,4],
        [1,3,2]
    ]
)

det_A = np.linalg.det(A)
print("Determinant of A is = ", det_A)

B = np.array([[1, 2],
              [3, 4]])

print("Determninant of B is = ", np.linalg.det(B))

Determinant of A is =  4.0
Determninant of B is =  -2.0000000000000004


In [ ]:
#Inverse of a matrix
A = np.array([[1, 3],
              [3, 5]])
I = np.linalg.inv(A)
print("Inverse of A is = ", I)

Inverse of A is =  [[-1.25  0.75]
 [ 0.75 -0.25]]


In [ ]:
#Adjoint of a amtrix
# Inverse(A) = 1/det(A) * Adj(A)
# Adj(A) = transpose of co-factos
# Adj(A) = Inverse(A)  *  Det(A)
import numpy as np
A = np.array ( [ [1,2],
                [3,4]
                ])

det_A = np.linalg.det(A)
Inv_A = np.linalg.inv(A)

Adj = Inv_A * det_A
print("Adjoint of A is = ", Adj.T)


Adjoint of A is =  [[ 4. -3.]
 [-2.  1.]]


In [ ]:
#Norm - L1 of a matrix - sum of absolute values of elements

import numpy as np
A = np.array ( [ [1,2],
                [3,4]
                ])
norm = np.linalg.norm(A,ord = 1)
print("Norm value is = ", norm)

Norm value is =  6.0


In [ ]:
#Norm - L1 of set of vectors

import numpy as np
A = np.array ( [1,2])
norm = np.linalg.norm(A,ord = 1)
print("Norm value is = ", norm)

Norm value is =  3.0


In [ ]:
#Norm - L2 of a square matrix -  sum of squares of elements and then its square root

import numpy as np
A = np.array ( [ [1,2],
                [3,4]
                ])
norm = np.linalg.norm(A,ord = 2)
print("Norm value is = ", norm)

Norm value is =  5.464985704219043


In [ ]:
#Finding square root
sqrt = np.sqrt(30)
print("Square root value of previous sum is = ", sqrt)
sqrt1 = np.sqrt(10)
print("Square root value of next sum is = ", sqrt1)

Square root value of previous sum is =  5.477225575051661
Square root value of next sum is =  3.1622776601683795


In [ ]:
#Norm - L2 of a non square matrix

import numpy as np
A = np.array ( [ [1],
                [3]
                ])
norm = np.linalg.norm(A,ord = 2)
print("Norm value is = ", norm)

Norm value is =  3.1622776601683795


In [ ]:
#Norm - L2 of a non square matrix

import numpy as np
A = np.array ( [2,2,1] )
norm = np.linalg.norm(A,ord = 2)
print("Norm value is = ", norm)

Norm value is =  3.0


In [ ]:
#Norm - L0 of a non square matrix - no of non-zero elements

import numpy as np
A = np.array ( [2,2,1,0,0,0,4] )
norm = np.linalg.norm(A,ord = 0)
print("Norm value is = ", norm)

Norm value is =  4.0


In [ ]:
# L infinity - gives the max abolute value
import numpy as np
A = np.array( [1,3,4] )
A1 = np.array ( [ [1,8,1],
                 [2,3,4]
])
norm= np.linalg.norm(A, ord=np.inf)
print("L infity value of A is = ", norm)

# L infity - it will sum all the elemetns in a row and returns the max sum value
B= np.linalg.norm(A1, ord=np.inf)
print("l infinity value of B is ", B)

L infity value of A is =  4.0
l infinity value of B is  10.0


In [9]:
#Pseudo Inverse of a matrix => A+ = [ Inverse of ( A.T @ A) ] @ A.T
import numpy as np
A= np.array ( [
       [1,2],
    [3,4],
    [5,6]
])
B = (A.T) @ A
print("First part of Formula : " , np.array(B))

inv_B = np.linalg.inv(B)
print("Inverse of B is = ", np.array(inv_B))

Pseudo_B = inv_B @ A.T
print("Pseudo inverse of the matrix is = ", Pseudo_B)

#Now finding it directly:
Pinv_A = np.linalg.pinv(A)
print("Directly finding Pseudo Inverse of A = ",Pinv_A)



First part of Formula :  [[35 44]
 [44 56]]
Inverse of B is =  [[ 2.33333333 -1.83333333]
 [-1.83333333  1.45833333]]
Pseudo inverse of the matrix is =  [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
Directly finding Pseudo Inverse of A =  [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [4]:
#print the diagonal elements
import numpy as np
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])

diag_ele = np.diag(A)
print("Diagonals elemets of a matrix = ",diag_ele)
print("Diaginal matrix : ",np.diag(diag_ele))


Diagonals elemets of a matrix =  [1 4]
Diaginal matrix :  [[1 0]
 [0 4]]


In [7]:
#Orthonormal of vectos. Its product should be 0 (so, perpendicular) and
#its norm should be 1. so, its orthonormal
import numpy as np
i = np.array( [ [1], [0], [0] ] )
j = np.array ( [ [0], [9], [0] ] )
k = np.array ( [ [0], [0], [1] ] )
orthogonal = 5
orthonormal = 5
if i.T @ j == 0:
  if j.T @ k ==0:
    if k.T @ i ==0:
      print("i,j,k are orthogonal")
      orthogonal = 0

if np.linalg.norm(i, ord=2) == 1:
  if np.linalg.norm(j, ord=2) == 1:
    if np.linalg.norm(k, ord=2) == 1:
      print("i,j,k are orthonormal")
      orthonormal = 1

if orthogonal == 0 and orthonormal == 1:
  print("i,j,k are both orthogonal and orthonormal to eachother")
elif orthonormal !=1:
  print("It is not orthonormal to each other")
elif orthogonal !=0:
  print( 'It is not orthogonal to each other')



i,j,k are orthogonal
It is not orthonormal to each other


In [16]:
# svd using the formula

import numpy as np
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
U, S, VT = np.linalg.svd(A)

print("U:\n", U)

# Create a Sigma matrix with the same dimensions as A
# and place the singular values S on its diagonal.
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(S)
print("Sigma:\n",Sigma)
print("V^T:\n", VT)

# Reconstruct A using U @ Sigma @ VT
print("Reconstructed A =\n", U @ Sigma @ VT)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma:
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
V^T:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Reconstructed A =
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
